language: javascript
os: linux
dist: bionic

services:
  - docker

before_install:
  - docker build -t react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true react-test npm test

after_success:
  # create production images
  - docker build -t antonije1/client ./client
  - docker build -t antonije1/nginx ./nginx
  - docker build -t antonije1/server ./server
  - docker build -t antonije1/worker ./worker
  # login into the docker hub
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push antonije1/client
  - docker push antonije1/nginx
  - docker push antonije1/server
  - docker push antonije1/worker

deploy:
  provider: elasticbeanstalk
  region: 'us-east-2'
  app: 'multi-docker'
  env: 'MultiDocker-env'
  bucket_name: 'elasticbeanstalk-us-east-2-789455171878'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
